sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run lint
  - echo lalalal
after_success:
  - npm run semantic-release
  - npm run report-coverage
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
